Feature/create slider component
digital-roots/vue-slider pull request #1
Opened 2024-04-15 17:56 UTC by andrecuenca

2024-04-15 22:33 UTC, jduque-dr requested changes

2024-04-15 22:33 UTC, jduque-dr commented on src/components/Slider.vue
> +    ${props.sliderColor} 100%)`;
bajale asi:
```suggestion
    ${props.sliderColor} 100%
  )`;
```

2024-04-15 22:33 UTC, jduque-dr commented on src/components/Slider.vue
> +      background-color: #C6C6C6;
esto esta de pasar a sass, variables

2024-04-24 14:05 UTC, jduque-dr approved these changes

2024-04-24 14:41 UTC, javier-dr approved these changes

2024-04-24 14:46 UTC, merged